# Generated by Django 2.2.1 on 2020-01-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('hname', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('lmark', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='file')),
                ('cno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=20)),
            ],
        ),
    ]
