# Generated by Django 2.2.1 on 2020-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
