# Generated by Django 2.2.1 on 2020-01-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citizen', '0004_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='request1',
        ),
    ]
