# Generated by Django 2.2.1 on 2020-01-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('bgrp', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('regno', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
