# Generated by Django 2.2.1 on 2020-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='photo',
            field=models.FileField(max_length=20, upload_to='file'),
        ),
    ]
