# Generated by Django 2.2.1 on 2020-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='officertextmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('oid', models.IntegerField()),
                ('msg', models.TextField()),
                ('encmsg', models.TextField(default='')),
                ('private', models.CharField(max_length=50)),
                ('public', models.CharField(max_length=50)),
            ],
        ),
    ]
